services:
  api-staging:
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: template-nextgen-api-staging
    ports:
      - "3334:3333"
    env_file:
      - ./server/.env.staging
    restart: unless-stopped
    environment:
      - WORKSPACE_DIR=${HOST_WORKSPACE_DIR:-/var/lib/shiply/workspace}
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ${HOST_WORKSPACE_DIR:-/var/lib/shiply/workspace}:${HOST_WORKSPACE_DIR:-/var/lib/shiply/workspace}
    networks:
      app-network:
        aliases:
          - api

  nginx-staging:
    build:
      context: .
      dockerfile: nginx.Dockerfile
    container_name: template-nextgen-nginx-staging
    ports:
      - "4445:80"
    restart: unless-stopped
    depends_on:
      - api-staging
    networks:
      - app-network

  runner-staging:
    image: oven/bun:1-alpine
    container_name: template-nextgen-runner-staging
    working_dir: /app
    command: sh -lc "apk add --no-cache docker-cli docker-cli-compose && bun run src/index.ts"
    environment:
      - API_URL=http://api-staging:3333
      - RUNNER_NAME=runner-staging
    volumes:
      - ./runner:/app:ro
      - /var/run/docker.sock:/var/run/docker.sock
      - ${HOST_WORKSPACE_DIR:-/var/lib/shiply/workspace}:${HOST_WORKSPACE_DIR:-/var/lib/shiply/workspace}
    depends_on:
      - api-staging
    restart: unless-stopped
    networks:
      - app-network

networks:
  app-network:
    driver: bridge


