services:
  api:
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: shiply-api-prod
    ports:
      - "12001:3333"
    env_file:
      - ./server/.env.prod
    restart: unless-stopped
    environment:
      - NODE_ENV=production
      - HOST=0.0.0.0
      - PORT=3333
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - app-network

  nginx:
    build:
      context: .
      dockerfile: nginx.Dockerfile
    container_name: shiply-nginx-prod
    ports:
      - "12002:80"
    restart: unless-stopped
    depends_on:
      - api
    environment:
      - NGINX_PORT=80
    networks:
      - app-network

networks:
  app-network:
    driver: bridge


