name: Release Shiply

on:
  push:
    branches:
      - main

permissions:
  contents: write
  issues: write
  pull-requests: write

concurrency:
  group: shiply-release-${{ github.ref }}
  cancel-in-progress: false

jobs:
  sonar:
    name: SonarQube Analysis
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: SonarSource/sonarqube-scan-action@v5
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
        with:
          args: >
            -Dsonar.projectKey=Shiply
            -Dsonar.projectName=Shiply

  docker:
    name: Build and push Docker images
    needs: [sonar]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push nginx (frontend)
        uses: docker/build-push-action@v6
        with:
          context: .
          file: nginx.Dockerfile
          push: true
          tags: |
            ${{ secrets.DOCKER_USERNAME }}/shiply-nginx:latest
            ${{ secrets.DOCKER_USERNAME }}/shiply-nginx:${{ github.sha }}

      - name: Build and push api (AdonisJS)
        uses: docker/build-push-action@v6
        with:
          context: ./server
          file: ./server/Dockerfile
          push: true
          tags: |
            ${{ secrets.DOCKER_USERNAME }}/shiply-api:latest
            ${{ secrets.DOCKER_USERNAME }}/shiply-api:${{ github.sha }}

      - name: Build and push runner (if Dockerfile exists)
        if: ${{ hashFiles('runner/Dockerfile') != '' }}
        uses: docker/build-push-action@v6
        with:
          context: ./runner
          file: ./runner/Dockerfile
          push: true
          tags: |
            ${{ secrets.DOCKER_USERNAME }}/shiply-runner:latest
            ${{ secrets.DOCKER_USERNAME }}/shiply-runner:${{ github.sha }}

  deploy:
    name: Deploy to server
    needs: [docker]
    runs-on: ubuntu-latest
    steps:
      - name: Install SSH key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.SERVER_SSH_KEY }}
          known_hosts: ${{ secrets.KNOWN_HOSTS }}

      - name: Deploy to server
        run: |
          ssh root@92.112.192.183 '
            set -e
            cd /app/Shiply &&
            git remote set-url origin git@github.com:Doxteur/Shiply.git &&
            git pull &&
            docker compose -f docker-compose.prod.yml pull &&
            docker compose -f docker-compose.prod.yml up -d --remove-orphans
          '

